title: Linux Kernel tyro
description: 一步一步往上爬，背着我的蜗牛壳，爬到葡萄架。
author: 李嘉图
language: zh-CN
timezone: Asia/Shanghai
deploy:
  type: git
  repository:
    github: https://github.com/Ricardo0106/Ricardo0106.github.io.git
    gitee: git@gitee.com:RicardoYoon/ricardoyoon.git
  branch: master
theme: fluid  

